remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Tomo101"
description: "A cryo-ET resource"
markdown: kramdown

just_the_docs:
  nav:
    - label: "Welcome page"
      url: "/"
      children:
        - label: "Some words about Cryo-Electron Tomography"
          url: "/some-words-cryo-et/"
        - label: "Sample types"
          url: "/sample-types/"
          children:
            - label: "In Situ VS Purified Samples"
              url: "/sample-types/in-situ-vs-purified-samples/"
              children:
                - label: "FIB-Milled Cellular Lamellae"
                  url: "/sample-types/in-situ-vs-purified-samples/fib-lamellae"
                - label: "Purified sample (e.g organelles, large viruses, etc)"
                  url: "/sample-types/in-situ-vs-purified-samples/purified-sample"
        - label: "Cryo-ET Data Collection Workflow"
          url: "/cryo-et-data-collection-workflow/"
        - label: "Challenges in Cryo-ET Data Collection"
          url: "/challenges-cryo-et/"
        - label: "Differences Between Cryo-ET and Single-Particle Analysis (SPA)"
          url: "/differences-cryo-et-spa/"
        - label: "Sub-Tomogram Averaging"
          url: "/subtomogram-averaging/"

    - label: "Dataset, software and resources"
      url: "/dataset-software-resources/"
      children:
        - label: "Dataset"
          url: "/dataset-software-resources/dataset/"
        - label: "Software"
          url: "/dataset-software-resources/software/"
        - label: "If you want to go further"
          url: "/dataset-software-resources/if-you-want-to-go-further/"

    - label: "Acknowledgments"
      url: "/acknowledgments/"
      children:
        - label: "Disclaimer"
          url: "/acknowledgments/disclaimer"

    - label: "Tutorial"
      url: "/tutorial/"
