remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

title: "Tomo101"
description: "A resource for cryo-ET"

# -- Just the Docs options --
# Defines the custom sidebar navigation.
just_the_docs:
  # The navigation key is an array of top-level items (each item has a label & url).
  nav:
    - label: "Welcome Page"
      url: "/"
      children:
        - label: "Some Words about Cryo-Electron Tomography"
          url: "/cryo-et/overview"
        - label: "Sample Types"
          url: "/cryo-et/sample-types"
          children:
            - label: "FIB-Milled Cellular Lamellae"
              url: "/cryo-et/fib-lamellae"
            - label: "Purified Samples"
              url: "/cryo-et/purified-sample"

    - label: "Cryo-ET Data Collection Workflow"
      url: "/data-collection/workflow"
      children:
        - label: "Challenges in Cryo-ET"
          url: "/data-collection/challenges"
        - label: "Differences between Cryo-ET & SPA"
          url: "/data-collection/differences"
        - label: "Sub-Tomogram Averaging"
          url: "/data-collection/subtomogram-averaging"

    - label: "Dataset, Software & Resources"
      url: "/data-collection/dataset-software-resources"

    - label: "Tutorial"
      url: "/tutorial/"

    - label: "Acknowledgments & Disclaimer"
      url: "/acknowledgments/"
