nav:
  - title: "Welcome"
    url: /
    children:
      - title: "Some Words about Cryo-ET"
        url: /some-words-cryo-et/
      - title: "Sample Types"
        url: /sample-types/
        children:
          - title: "In Situ vs Purified Samples"
            url: /sample-types/in-situ-vs-purified-samples/
      - title: "Cryo-ET Data Collection Workflow"
        url: /cryo-et-data-collection-workflow/
      - title: "Challenges in Cryo-ET"
        url: /challenges-cryo-et/
      - title: "Differences Between Cryo-ET and SPA"
        url: /differences-cryo-et-spa/
      - title: "Sub-Tomogram Averaging"
        url: /subtomogram-averaging/
  - title: "Dataset, Software, and Resources"
    url: /dataset-software-resources/
  - title: "Acknowledgments"
    url: /acknowledgments/
    children:
      - title: "Disclaimer"
        url: /acknowledgments/disclaimer/
  - title: "Tutorial"
    url: /tutorial/
