nav:
  - title: "Welcome Page"
    url: /
    children:
      - title: "Some Words about Cryo-Electron Tomography"
        url: /some-words-cryo-et/
      - title: "Sample Types"
        url: /sample-types/
        children:
          - title: "In Situ vs Purified Samples"
            url: /sample-types/in-situ-vs-purified-samples/
      - title: "Cryo-ET Data Collection Workflow"
        url: /cryo-et-workflow/
      - title: "Challenges in Cryo-ET Data Collection"
        url: /challenges-cryo-et/
      - title: "Differences Between Cryo-ET and Single-Particle Analysis (SPA)"
        url: /differences-cryo-et-spa/
      - title: "Sub-Tomogram Averaging"
        url: /subtomogram-averaging/

  - title: "Dataset, Software, and Resources"
    url: /dataset-software-resources/
    children:
      - title: "Dataset"
        url: /dataset-software-resources/dataset/
      - title: "Software"
        url: /dataset-software-resources/resources/
      - title: "If you want to go further"
        url: /dataset-software-resources/further/

  - title: "Acknowledgments"
    url: /acknowledgments/

  - title: "Tutorial"
    url: /tutorial/
